[tool.poetry]
name = "nwp-demo"
# Keep only Major and Minor version in this configuration,
# the patch version is calculated when releasing the library
version = "1.0"
description = "Demo scripts and notebooks for reading and processing forecast data using Polytope."
authors = ["MeteoSwiss"]
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
meteodata-lab = {version = "*", extras = ["polytope", "regrid"] }
pyfdb = "*"
fdb-utils = { git = "https://github.com/MeteoSwiss/fdb-utils.git"}

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = "."

[tool.yapf]
based_on_style = "pep8"
column_limit = "120"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
