sirocco:
  compiler: [gcc]
  specs:
    - python@3.14
  unify: true
  views:
    bare:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
    app:
      uenv:
        env_vars:
          set:
            - VIRTUAL_ENV: "/user-tools/sirocco_venv"
            - VIRTUAL_ENV_PROMPT: "༄ sirocco ༄"
          prepend_path:
            - PATH: "/user-tools/sirocco_venv/bin"
