name: fdb
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: v1.2.0
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: v2026.06.0
description: MCH FDB uenv
version: 2
