fdb:
  compiler: [gcc]
  unify: when_possible
  packages: []
  specs:
  - fdb@=5.19.2 backends=lustre
  - gribjump@=0.10.3
  - eckit@=2.0.2 linalg=none compression=lz4 +curl +ssl
  - metkit@=1.16.3-levelist
  - eccodes@=2.46.0 jp2k=none ~fortran +pthreads +aec +geo
  - ecbuild@=3.13.1
  - python@=3.11.14
  variants:
  - ~mpi
  views:
    realtime:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
        env_vars:
          set:
            - FDB_HOME:          "$@view_path@"
            - FDB5_HOME:         "$@view_path@"
            - ECKIT_HOME:        "$@view_path@"
            - GRIB_DEFINITION_PATH: "$@mount@/data/share/eccodes-cosmo-mars/definitions:\
                                     $@mount@/venvs/fdb/share/eccodes-cosmo-resources/definitions:\
                                     $@mount@/env/fdb/share/eccodes/definitions"
            # NOTE: this assumes that the fdb config names match the view names
            - FDB5_CONFIG_FILE:  "$@mount@/meta/recipe/meta/private/fdb_config/$@view_name@.yaml"
            - FDB_ENABLE_GRIBJUMP: "1"
            - AUTO_LOAD_PLUGINS:   "1"
            - ECCODES_ECKIT_GEO:   "1"
          prepend_path:
            - PATH: "$@mount@/venvs/fdb/bin/"
    rea-l-ch1:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
        env_vars:
          set:
            - FDB_HOME:          "$@view_path@"
            - FDB5_HOME:         "$@view_path@"
            - ECKIT_HOME:        "$@view_path@"
            - GRIB_DEFINITION_PATH: "$@mount@/data/share/eccodes-cosmo-mars/definitions:\
                                     $@mount@/venvs/fdb/share/eccodes-cosmo-resources/definitions:\
                                     $@mount@/env/fdb/share/eccodes/definitions"
            # NOTE: this assumes that the fdb config names match the view names
            - FDB5_CONFIG_FILE:  "$@mount@/meta/recipe/meta/private/fdb_config/$@view_name@.yaml"
            - FDB_ENABLE_GRIBJUMP: "1"
            - AUTO_LOAD_PLUGINS:   "1"
            - ECCODES_ECKIT_GEO:   "1"
          prepend_path:
            - PATH: "$@mount@/venvs/fdb/bin/"
            - PYTHONPATH: "$@view_path@/share/python"
    remote-devt:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
        env_vars:
          set:
            - FDB_HOME:          "$@view_path@"
            - FDB5_HOME:         "$@view_path@"
            - ECKIT_HOME:        "$@view_path@"
            - GRIB_DEFINITION_PATH: "$@mount@/data/share/eccodes-cosmo-mars/definitions:\
                                     $@mount@/venvs/fdb/share/eccodes-cosmo-resources/definitions:\
                                     $@mount@/env/fdb/share/eccodes/definitions"
            # NOTE: this assumes that the fdb config names match the view names
            - FDB5_CONFIG_FILE:  "$@mount@/meta/recipe/meta/private/fdb_config/$@view_name@.yaml"
            - FDB_ENABLE_GRIBJUMP: "1"
            - AUTO_LOAD_PLUGINS:   "1"
            - ECCODES_ECKIT_GEO:   "1"
          prepend_path:
            - PATH: "$@mount@/venvs/fdb/bin/"
    remote-depl:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
        env_vars:
          set:
            - FDB_HOME:          "$@view_path@"
            - FDB5_HOME:         "$@view_path@"
            - ECKIT_HOME:        "$@view_path@"
            - GRIB_DEFINITION_PATH: "$@mount@/data/share/eccodes-cosmo-mars/definitions:\
                                     $@mount@/venvs/fdb/share/eccodes-cosmo-resources/definitions:\
                                     $@mount@/env/fdb/share/eccodes/definitions"
            # NOTE: this assumes that the fdb config names match the view names
            - FDB5_CONFIG_FILE:  "$@mount@/meta/recipe/meta/private/fdb_config/$@view_name@.yaml"
            - FDB_ENABLE_GRIBJUMP: "1"
            - AUTO_LOAD_PLUGINS:   "1"
            - ECCODES_ECKIT_GEO:   "1"
          prepend_path:
            - PATH: "$@mount@/venvs/fdb/bin/"
