#!/bin/bash
# Post-install for the uenv:
#  - Fetch eccodes/GRIB shared definitions
#  - Install Poetry and create a venv for FDB tooling
#  - Expand metkit param/language tables (adds ICON models/streams/params)
#  - Configure env vars per view
#  - For 'rea-l-ch1' only: install a tiny Python helper (shortName -> paramId)

set -e

# --- Fetch GRIB/eccodes resources  ----------------------------------------
rm -rf {{ env.mount }}/data/share
mkdir -p {{ env.mount }}/data/share
pushd {{ env.mount }}/data/share
# eccodes cosmo definitions: since the updated defs are not published by DWD yet,
# they are instead provided by the corresponding internal python package; see var
# 'eccodes_cosmo_resources_path' below
#wget https://opendata.dwd.de/weather/lib/grib/eccodes_definitions.edzw-2.38.3-1.tar.bz2
#bunzip2  eccodes_definitions.edzw-2.38.3-1.tar.bz2
#tar xvf eccodes_definitions.edzw-2.38.3-1.tar
#rm eccodes_definitions.edzw-2.38.3-1.tar
git clone -b v0.0.4 https://github.com/MeteoSwiss/eccodes-cosmo-mars.git
popd

# --- Tooling: locate Python, install Poetry, create venv for FDB tooling ---
install_root={{ env.mount }}/linux-zen3/
python_exe=$(find $install_root -path "*/bin/python3.11" -type f)

curl -sSL https://install.python-poetry.org | POETRY_HOME={{ env.mount }} $python_exe -

# NOTE: in environments.yaml, the specs of the env variables GRIB_DEFINITION_PATH and PATH assume that fdb is installed under /user-environment/venvs/fdb
pushd {{ env.mount }}/meta/recipe/meta/private/
rm -rf  {{ env.mount }}/venvs/
mkdir -p {{ env.mount }}/venvs/
$python_exe -m venv {{ env.mount }}/venvs/fdb
source {{ env.mount }}/venvs/fdb/bin/activate
{{ env.mount }}/bin/poetry install
popd

# determine path of eccodes cosmo resources from python package
eccodes_cosmo_resources_path=$(python -c "import eccodes_cosmo_resources as res; print(res.get_definitions_path())")

# --- Expand metkit tables with ICON parameter, model, and stream definitions --
metkit_dir=$(dirname $(find $install_root -name language.yaml))

python {{ env.mount }}/meta/recipe/meta/private/expand_params.py ${metkit_dir}/paramids.yaml ${eccodes_cosmo_resources_path}/grib2/shortName.def,${eccodes_cosmo_resources_path}/grib2/localConcepts/edzw/shortName.def
python {{ env.mount }}/meta/recipe/meta/private/expand_language.py ${metkit_dir}/language.yaml

# --- rea-l-ch1 only: install Python helper for shortName → paramId mapping ---
# Makes it importable via: from uenv_param_map import shortname_to_paramid
helper_src="{{ env.mount }}/meta/recipe/meta/private/uenv_param_map.py"
# NOTE: this path is used in the PYTHONPATH env var in environments.yaml
helper_dir="{{ env.mount }}/env/rea-l-ch1/share/python"
mkdir -p "$helper_dir"
cp -f "$helper_src" "$helper_dir/"
