name: icon
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 122a2b98e149d96451afc49bc617f348b1bd1ad2
modules: true
description: "Compilers and libraries required to build ICON"
version: 2
