fdb:
  compiler:
    - toolchain: gcc
      spec: gcc@13.3
  unify: when_possible
  mpi: null
  packages: []
  specs:
  - fdb@=5.16.2
  - eckit@=1.28.8 linalg=none
  - metkit@=1.11.22
  - eccodes@=2.38.3 jp2k=none ~fortran
  - ecbuild@=3.10.0
  - python@=3.11.6
  variants:
  - ~mpi
  views:
    fdb:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
