name: icon
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.1
  packages:
    c2sm:
      repo: https://github.com/C2SM/spack-c2sm.git
      commit: v1.1_dev # TODO: pin this to a tag
    builtin:
      repo: https://github.com/spack/spack-packages.git
      tag: v2026.06.0
modules: true
description: "Compilers and libraries required to build ICON"
version: 2
