icon:
  compiler: [gcc, nvhpc]
  network:
    mpi: cray-mpich@9.1.0 +cuda %c,cxx,fortran=nvhpc ^libfabric@2 +gdrcopy %c=nvhpc
    specs: [ xpmem ]
  unify: when_possible
  specs:
    - python@3.13 %c,cxx=gcc ^libffi %c,cxx=gcc ^expat %c=gcc ^libmd %c=gcc ^gettext %c,cxx=gcc
    - python-venv
    - cuda@13.1
    - eccodes@2.36.4 +fortran jp2k=jasper %c,cxx,fortran=nvhpc
    - eccodes-cosmo-resources@2.36.0.3 ^eccodes %c,cxx,fortran=nvhpc
    - hdf5@1.14.6 +fortran+hl+szip+threadsafe %c,fortran=nvhpc
    - netcdf-c@4.9.3 %c,cxx=nvhpc
    - netcdf-fortran@4.6.2 %c,fortran=nvhpc
    - boost
    - openblas %c,cxx,fortran=nvhpc
    - serialbox +fortran +netcdf %c,cxx,fortran=nvhpc
    # for validation
    - cdo
    # everything needed for nccl on SS11
    - nccl@2.29.2
    - nccl-tests
    - aws-ofi-nccl@1.17.2
    # extras
    - libfyaml
    - zlib-ng
    - cmake
    - findutils
  variants:
    - +mpi
    - +cuda
    - cuda_arch=90
  views:
    default:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
      exclude:
        - python-venv
