eobs-lab:
  compiler: [gcc]
  specs:
    - python@3.12
  unify: true
  views:
    lab:
      link: roots
      uenv:
        add_compilers: false
        env_vars:
          set:
            - VIRTUAL_ENV: "$@mount@/venv"
          prepend_path:
            - PATH: "$@mount@/venv/bin"
