eobs-lab:
  compiler:
    - toolchain: gcc
      spec: gcc@12
  specs:
    - python@3.12
  unify: true
  views:
    eobs-lab:
      uenv:
        add_compilers: false
        env_vars:                          
          set:
            - VIRTUAL_ENV: "/user-environment/eobs-lab_venv"
          prepend_path:
            - PATH: "/user-environment/eobs-lab_venv/bin"
    
